### ISSUE TITLE
Can't identify page to modify

### ISSUE THREAD

**Issue by aetherfaerber** [Osndok/zim-plugin-append#2]
It always ends up raising the 
`Exception: you must somehow identify a page to modify`

After installing the plugin the first output line read
`NotebookInfo= None`
and was followed by a trace to the Exception mentioned above.

I went to change the "Default notebook" option in the main file to an existing Notebook. Now the notebook seems to be identified but still the page isn't.

```
nils@Igorth:~$ zim --plugin append j "Went to buy bread."
NotebookInfo= <NotebookInfo: file:///home/nils/Log/>
ERROR: Exception in main()
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/zim/main.py", line 446, in main
    obj.run()
  File "/home/nils/.local/share/zim/plugins/append.py", line 175, in run
    raise Exception, 'you must somehow identify a page to modify'
Exception: you must somehow identify a page to modify
```

This even happens when I define a notebook and page:

```
nils@Igorth:~$ zim --plugin append notebook=Log page=Bakery "Went to buy bread."
NotebookInfo= <NotebookInfo: file:///home/nils/Log>
ERROR: Exception in main()
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/zim/main.py", line 446, in main
    obj.run()
  File "/home/nils/.local/share/zim/plugins/append.py", line 175, in run
    raise Exception, 'you must somehow identify a page to modify'
Exception: you must somehow identify a page to modify
```

Any ideas? Is my syntax correct?
This is zim 0.62.

**Comment by Osndok** [comment]
It might just be lost in github, but it looks like you are missing the '-' in the option flags, and to append a literal string you need the '-l' or '--literal' before it.

Try:
```
zim --plugin append -j -l "Went to buy bread."
-or-
zim --plugin append --notebook=Log --page=Bakery --literal="Went to buy bread."
```

**Comment by aetherfaerber** [comment]
Aah yes. Can't believe I didn't think of that and didn't try it.

..it works and it's awesome. Thank you!

**Comment by Osndok** [comment]
My pleasure. I appreciate the feedback, and I have used this initiative to add a bit more to the front-page README that might help others!
