### ISSUE TITLE
Could not load commandline command for plugin "append"

### ISSUE THREAD

**Issue by et2010** [Osndok/zim-plugin-append#3]
I cannot run this plugin in cmd, and when I checked `zim.exe.log`, it got following message:

```
INFO: Locale set to: Chinese (Simplified)_China.936
Could not load commandline command for plugin "append"
```

BTW I run this in a cmd window as admin, otherwise the log cannot be accessed, and sorry for my poor English.

**Comment by Osndok** [comment]
Hi. Thank you for your interest. I take it that you are using Microsoft Windows, so I don't know how much help I can actually provide.

It looks like zim simply cannot find the plugin. I would double check that the append.py file is in the correct place for *Windows* (which is probably a different place than for linux).

According to the below link, it should be in `%APPDATA%/zim/data/zim/plugins/`, but I don't know what APPDATA expands to, and a quick google search indicates it might be hidden.

* http://superuser.com/questions/1022638/plugin-directory-for-zim-wiki-0-63-on-windows-10

I hope that helps. If you find a path that works, please add it to the zim plugins wiki... at the moment it only has the Linux path.

**Comment by et2010** [comment]
Thanks for your detailed reply.  I think it's really cool to run zim without a gui. I can do lots of things with it and ahk scripts, only if you can help me to make it work on Windows.

>According to the below link, it should be in %APPDATA%/zim/data/zim/plugins/, but I don't know what APPDATA expands to, and a quick google search indicates it might be hidden.

That path you mentioned is the default path for custom plugins and that is where my downloaded plugins go. Other plugins all work well, so I don't think the path is an issue.

>If you find a path that works, please add it to the zim plugins wiki... at the moment it only has the Linux path.

As for the wiki, its description about the plugin path is also valid on Windows, only note that the equivalent of `~` on Windows is `C:\Users\currentuser` (change `currentuser` to your desired username) by default. You can set the `%HOME%` variable to any path you want.

Before I wrote this, I tried a fresh install and set my default locale to English (it's really buggy when use other locales for a gtk app on Windows), but still can't make `append.py` work. This time the error log is gone but nothing happened, no text appended.

Let me know if you need any other info to solve this issue.

**Comment by Osndok** [comment]
Perhaps running zim with the '--debug' flag would give more helpful information?

**Comment by et2010** [comment]
I tried that '--debug' flag, no debug message was shown. But I noticed that `zim.log` (not `zim.exe.log`) captured the error message: `Could not load commandline command for plugin "append"`

**Comment by Osndok** [comment]
Without more detail, it *still* sounds like Zim simply cannot find the file. And I'm sorry... but, not being a windows user, I don't think I'll be able to help you fix this. I *do* know that at least one Windows user got it to work, however, so I know it's possible, just what the issue is, though (like... line endings, and paths). I wish you luck!

**Comment by Osndok** [comment]
Looks like this happens in Fedora 25, possibly related to the use of __import__ , and zim squelches the actual error message...

**Comment by Osndok** [comment]
If you can add the missing line from this patch, it might tell you what is actually wrong:

https://launchpadlibrarian.net/314628633/zim-0.65-more-plugin-error-detail.diff

In my case, it was missing the "dateutils" python package... and it might be in yours too! ...but I don't know how windows python packages are installed. :(

**Comment by MirisWisdom** [comment]
For the lost souls who come across this pre-pandemic issue and experience it:

If you've cloned this repository to your plugins folder, make sure the folder name is `append` and not `zim-plugin-append`.
